version: '3.7'

services:

  workload-generator-ms:
    image: aioann01/iot_workload_generator:first
    volumes:
      - /c/Users/andre/Dev/WorkloadGenerator/WorkloadGenerator_ms/resources/configs_file.json:/home/configs/configs_file.json
      - /c/Users/andre/Dev/WorkloadGenerator/WorkloadGenerator_ms/resources/configs_file_ALL.json:/home/configs/configs_file_ALL.json
      - /c/Users/andre/Dev/WorkloadGenerator/WorkloadGenerator_ms/resources/workloadGenerator.properties:/home/configs/workloadGenerator.properties
      - /c/Users/andre/Dev/WorkloadGenerator/WorkloadGenerator_ms/resources/beach-water-quality-automated-sensors-1.csv:/home/resources/beach-water-quality-automated-sensors-1.csv
    environment:
      - JAVA_OPTS="-Xmx3G -Xms3G"
      - SERVER_PORT=8091
      - SSO.SERVICE_PORT=809
      - SSO.SERVICE.IP=sso-ms
      - AUTHORIZATION.ENABLED=false
      - logging.level.*=INFO
      - LOGGING_FILE=/home/logs/server.log
      - logging.level.cy.cs.ucy.ade.aioann01.WorkloadGenerator.Model.MockSensorData.*=TRACE
      - logging.level.cy.cs.ucy.ade.aioann01.WorkloadGenerator.Services.SendServices.*=TRACE
      - CONFIGS_DIRECTORY=/home/configs/
      - RESOURCES_DIRECTORY=/home/resources/
    ports:
      - "8091:8091"
    container_name: workloadGenerator_ms
    networks:
      - workloadGenerator-network  


  #sensors-ms:
   # build:
    #  context: .
     # dockerfile: Sensors_ms/Dockerfile
    #ports:
    #  - "8092:8092"
    #  - "8002:8002"
   # networks:
   #   - workloadGenerator-network    
   # container_name: sensors_ms
  
  
  http-server:
    image: aioann01/iot_http_server:latest
    environment:
      - server.port=8095
      - logging.level=INFO,DEBUG,ERROR
      - LOGGING_FILE=/home/logs/server.log
      - logging.level.web=DEBUG
    ports:
      - "8095:8095"
    networks:
      - workloadGenerator-network  
    container_name: httpServer


  #mqtt-subscriber-client-ms:
   # build:
    #  context: .
     # dockerfile: MqttSubscriberClient/Dockerfile
    #ports:
    #  - "8094:8094"
    #  - "8004:8004"
    #container_name: mqttSubscriberClient_ms
    #networks:
    #  - workloadGenerator-network  
  
    
    
  #mqtt-broker:
  #  image: eclipse-mosquitto
  #  ports:
  #    - "1883:1883"
  #    - "9001:9001"
  #  container_name: mqttBroker
  #  networks:
  #    - workloadGenerator-network  
  
  
  #sso-ms:
  #  build:
  #    context: .
  #    dockerfile: SSO_ms/Dockerfile
  #  ports:
  #    - "8090:8090"
  #    - "8000:8000"
  #  networks:
  #    - workloadGenerator-network    
  #  container_name: sso_ms
      
networks:
   workloadGenerator-network:
     driver: bridge       
    
   