FROM openjdk:8-jdk-alpine
COPY ./KafkaConsumerClient/target/KafkaConsumerClient-1.0.0-SNAPSHOT.jar /home/KafkaConsumerClient-1.0.0-SNAPSHOT.jar
CMD ["java","-jar", "/home/KafkaConsumerClient-1.0.0-SNAPSHOT.jar"]
EXPOSE 8096 8006