pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
				dir('Workload Generator'){
					sh "pwd"}				
				sh 'build'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}