FROM openjdk:8-jdk-alpine
COPY ./MqttSubscriberClient/target/MqttSubscriberClient-1.0.0-SNAPSHOT.jar /home/MqttSubscriberClient-1.0.0-SNAPSHOT.jar
CMD ["java","-jar", "/home/MqttSubscriberClient-1.0.0-SNAPSHOT.jar"]
EXPOSE 8094 8004